/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import controller.Controller;
import vue.MainWindowJFrame;

import javax.swing.*;

import client.Client;
import console.Console;
import vue.composant.FlatComboBox;
import vue.panel.ResearchPanel;

public class App {
    /**
     * The host to connect to.
     */
    private static final String HOST = "localhost";
    /**
     * The port to connect to.
     */
    private static final int PORT = 12345;

    public static void main(String[] args) {
        ResearchPanel researchPanel = new ResearchPanel();
        FlatComboBox stationDepartList = new FlatComboBox(new String[]{}), stationArriveList = new FlatComboBox(new String[]{});
        //TODO: créer les bouttons ici puis les passer en paramètre
        Client client = new Client(HOST, PORT, researchPanel, stationDepartList, stationArriveList);
        Controller controller = new Controller(client);
        researchPanel.addObserver(client);
        stationDepartList.addObserver(client);
        stationArriveList.addObserver(client);
        if (client.isConnected()) {
            client.start();
            SwingUtilities.invokeLater(() -> new MainWindowJFrame(controller, researchPanel, stationDepartList, stationArriveList));
            new Console(client).start();
        } else {
            new Console(null).start();
        }
    }
}
