/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import client.Client;
import console.Console;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }
    public static void main(String[] args) {
        new Console(new Client("localhost", 12345));
    }
}
