/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import app.vue.MainWindowJFrame;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }
    public static void main(String[] args) {

        new MainWindowJFrame();
        //System.out.println(new App().getGreeting());
    }
}
